services:
  - type: web
    name: rbx-luau-decompiler-api
    runtime: node
    repo: https://github.com/Roll-It0/Test
    plan: free
    startCommand: node src/server.js
    envVars:
      - key: NODE_ENV
        value: production
