const shapes = {
  ABC: "ABC",
  ABx: "ABx",
  AsBx: "AsBx",
  Ax: "Ax"
};

const lua51 = {
  MOVE: { id: 0, shape: shapes.ABC, flags: { move: true } },
  LOADK: { id: 1, shape: shapes.ABx, flags: { loadConst: true } },
  LOADBOOL: { id: 2, shape: shapes.ABC, flags: {} },
  LOADNIL: { id: 3, shape: shapes.ABC, flags: {} },
  GETUPVAL: { id: 4, shape: shapes.ABC, flags: {} },
  GETGLOBAL: { id: 5, shape: shapes.ABx, flags: { loadConst: true } },
  GETTABLE: { id: 6, shape: shapes.ABC, flags: {} },
  SETGLOBAL: { id: 7, shape: shapes.ABx, flags: { storeGlobal: true } },
  SETUPVAL: { id: 8, shape: shapes.ABC, flags: {} },
  SETTABLE: { id: 9, shape: shapes.ABC, flags: {} },
  NEWTABLE: { id: 10, shape: shapes.ABC, flags: {} },
  SELF: { id: 11, shape: shapes.ABC, flags: {} },
  ADD: { id: 12, shape: shapes.ABC, flags: { arithmetic: true } },
  SUB: { id: 13, shape: shapes.ABC, flags: { arithmetic: true } },
  MUL: { id: 14, shape: shapes.ABC, flags: { arithmetic: true } },
  DIV: { id: 15, shape: shapes.ABC, flags: { arithmetic: true } },
  MOD: { id: 16, shape: shapes.ABC, flags: { arithmetic: true } },
  POW: { id: 17, shape: shapes.ABC, flags: { arithmetic: true } },
  UNM: { id: 18, shape: shapes.ABC, flags: {} },
  NOT: { id: 19, shape: shapes.ABC, flags: {} },
  LEN: { id: 20, shape: shapes.ABC, flags: {} },
  CONCAT: { id: 21, shape: shapes.ABC, flags: {} },
  JMP: { id: 22, shape: shapes.AsBx, flags: { jump: true } },
  EQ: { id: 23, shape: shapes.ABC, flags: { compare: true } },
  LT: { id: 24, shape: shapes.ABC, flags: { compare: true } },
  LE: { id: 25, shape: shapes.ABC, flags: { compare: true } },
  TEST: { id: 26, shape: shapes.ABC, flags: {} },
  TESTSET: { id: 27, shape: shapes.ABC, flags: {} },
  CALL: { id: 28, shape: shapes.ABC, flags: { call: true } },
  TAILCALL: { id: 29, shape: shapes.ABC, flags: { call: true } },
  RETURN: { id: 30, shape: shapes.ABC, flags: { ret: true } },
  FORLOOP: { id: 31, shape: shapes.AsBx, flags: { loop: true } },
  FORPREP: { id: 32, shape: shapes.AsBx, flags: { loop: true } },
  TFORLOOP: { id: 33, shape: shapes.ABC, flags: { loop: true } },
  SETLIST: { id: 34, shape: shapes.ABC, flags: {} },
  CLOSE: { id: 35, shape: shapes.ABC, flags: {} },
  CLOSURE: { id: 36, shape: shapes.ABx, flags: { closure: true } },
  VARARG: { id: 37, shape: shapes.ABC, flags: {} }
};

const luau = {
  MOVE: { id: 0, shape: shapes.ABC, flags: { move: true } },
  LOADK: { id: 1, shape: shapes.ABx, flags: { loadConst: true } },
  GETGLOBAL: { id: 2, shape: shapes.ABx, flags: { loadConst: true } },
  SETGLOBAL: { id: 3, shape: shapes.ABx, flags: { storeGlobal: true } },
  GETUPVAL: { id: 4, shape: shapes.ABC, flags: {} },
  SETUPVAL: { id: 5, shape: shapes.ABC, flags: {} },
  GETIMPORT: { id: 6, shape: shapes.ABx, flags: { import: true } },
  CALL: { id: 7, shape: shapes.ABC, flags: { call: true } },
  RETURN: { id: 8, shape: shapes.ABC, flags: { ret: true } },
  JUMP: { id: 9, shape: shapes.AsBx, flags: { jump: true } },
  JUMPBACK: { id: 10, shape: shapes.AsBx, flags: { loop: true } },
  FORGLOOP: { id: 11, shape: shapes.AsBx, flags: { loop: true } },
  FORGPREP: { id: 12, shape: shapes.AsBx, flags: { loop: true } },
  ADD: { id: 13, shape: shapes.ABC, flags: { arithmetic: true } },
  SUB: { id: 14, shape: shapes.ABC, flags: { arithmetic: true } },
  MUL: { id: 15, shape: shapes.ABC, flags: { arithmetic: true } },
  DIV: { id: 16, shape: shapes.ABC, flags: { arithmetic: true } },
  MOD: { id: 17, shape: shapes.ABC, flags: { arithmetic: true } },
  POW: { id: 18, shape: shapes.ABC, flags: { arithmetic: true } },
  CONCAT: { id: 19, shape: shapes.ABC, flags: {} },
  NOT: { id: 20, shape: shapes.ABC, flags: {} },
  LENGTH: { id: 21, shape: shapes.ABC, flags: {} },
  NEWCLOSURE: { id: 22, shape: shapes.ABx, flags: { closure: true } },
  FASTCALL: { id: 23, shape: shapes.ABC, flags: { call: true } },
  FASTCALL1: { id: 24, shape: shapes.ABC, flags: { call: true } },
  FASTCALL2: { id: 25, shape: shapes.ABC, flags: { call: true } },
  FASTCALL2K: { id: 26, shape: shapes.ABC, flags: { call: true } }
};

module.exports = { shapes, lua51, luau };
