const OP_CODES = {
    0:  { name: "NOP",       format: "NONE" },
    1:  { name: "BREAK",     format: "NONE" },
    2:  { name: "LOADNIL",   format: "A" },
    3:  { name: "LOADB",     format: "ABC" },
    4:  { name: "LOADN",     format: "ABx" },
    5:  { name: "LOADK",     format: "ABx" },
    6:  { name: "MOVE",      format: "AB" },
    7:  { name: "GETGLOBAL", format: "ABx" },
    8:  { name: "SETGLOBAL", format: "ABx" },
    9:  { name: "GETUPVAL",  format: "AB" },
    10: { name: "SETUPVAL",  format: "AB" },
    11: { name: "CLOSEUPVALS",format: "A" },
    12: { name: "GETIMPORT", format: "ABx" },
    13: { name: "GETTABLE",  format: "ABC" },
    14: { name: "SETTABLE",  format: "ABC" },
    15: { name: "GETTABLEKS",format: "ABC" },
    16: { name: "SETTABLEKS",format: "ABC" },
    17: { name: "GETTABLEN", format: "ABC" },
    18: { name: "SETTABLEN", format: "ABC" },
    19: { name: "NEWCLOSURE",format: "ABx" },
    20: { name: "NAMECALL",  format: "ABC" },
    21: { name: "CALL",      format: "ABC" },
    22: { name: "RETURN",     format: "AB" },
    23: { name: "JUMP",       format: "sBx" },
    24: { name: "JUMPIF",     format: "AsBx" },
    25: { name: "JUMPIFNOT",  format: "AsBx" },
    26: { name: "JUMPIFEQ",   format: "AsBx" },
    27: { name: "JUMPIFNOTEQ",format: "AsBx" },
    28: { name: "ADD",        format: "ABC" },
    29: { name: "SUB",        format: "ABC" },
    30: { name: "MUL",        format: "ABC" },
    31: { name: "DIV",        format: "ABC" },
    32: { name: "MOD",        format: "ABC" },
    33: { name: "POW",        format: "ABC" },
    34: { name: "NOT",        format: "AB" },
    35: { name: "LEN",        format: "AB" },
    36: { name: "UNM",        format: "AB" },
    37: { name: "AND",        format: "ABC" },
    38: { name: "OR",         format: "ABC" },
    39: { name: "FORNPREP",   format: "AsBx" },
    40: { name: "FORNLOOP",   format: "AsBx" },
    41: { name: "FORGPREP",   format: "AsBx" },
    42: { name: "FORGLOOP",   format: "AsBx" },
    43: { name: "FASTCALL",   format: "ABC" }
};

module.exports = OP_CODES;
